### ISSUE TITLE
Offline use

### ISSUE THREAD

**Issue by jordyno** [thomcc/equirect-to-cubemap-faces#14]
You mentioned your code could be possibly used in the future offline. I can imagine providing clients with a generated Powershell script to use some SDK to process your functions on a given file? Could you please give me just some general idea / steps to elaborate?

**Comment by thomcc** [comment]
It could work offline in that you could probably use it as a node module, if you can shim the canvas or ImageData api well enough. (see https://github.com/Automattic/node-canvas).

I don't know if I think it's able to use in a convenient manner the way you describe, since your clients would need to install node.js first. Maybe you could use it in an electron app, though (in which case you wouldn't need the node-canvas dependency).

Closing since I don't really think there's a way I can better support this than I currently do.

**Comment by jordyno** [comment]
Thanks a lot Thom!
