### ISSUE TITLE
flipped cubes

### ISSUE THREAD

**Issue by jordyno** [thomcc/equirect-to-cubemap-faces#9]
Resulting cube faces are flipped along y-axis, wonder how to fix that and if anyone else is getting the same result?

**Comment by thomcc** [comment]
You could probably fix it in your shader (If it's every face I'd say your shader probably has an issue). Or by flipping the faces after the call.

I've been meaning to release a version that allows you to configure this (e.g. which faces are flipped along X and Y), though. I'll try and finish that after work today.

**Comment by jordyno** [comment]
Thanks for the quick reply! Yes I thought about flipping it after the call, but wanted to avoid extra cpu usage if it could be done during the conversion directly. Trying to emulate Marzipano Tool and there are many cube faces to be created at various tile sizes, so I am trying to find the most efficient solution.

**Comment by thomcc** [comment]
Fixed in commit acd99d9. This is really the same bug as #8, I've fixed both (in a slightly more mathematically correct way than the PR). If you use the release 2.0.0 it should work for you without issues. Users who want the old behavior can get it via passing `{ flipTheta: true }` as the last argument to whichever function.
